/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author thebe
 */
public class EmpleadoConsultarInformacion extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadoConsultarInformacion
     */
    public EmpleadoConsultarInformacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        numCuentaField1 = new javax.swing.JTextField();
        limpiarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numCuentaField2 = new javax.swing.JTextField();
        numCuentaField3 = new javax.swing.JTextField();
        numCuentaField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        numCuentaField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        numCuentaField6 = new javax.swing.JTextField();
        limpiarBtn1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Busque Al Cliente por DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Condensed", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ingrese DNI del Cliente: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 30));

        numCuentaField1.setBackground(new java.awt.Color(255, 255, 255));
        numCuentaField1.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField1.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField1.addActionListener(this::numCuentaField1ActionPerformed);
        jPanel1.add(numCuentaField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, 30));

        limpiarBtn.setBackground(new java.awt.Color(204, 0, 0));
        limpiarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarBtn.setText("Limpiar");
        limpiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarBtn.setDefaultCapable(false);
        limpiarBtn.addActionListener(this::limpiarBtnActionPerformed);
        jPanel1.add(limpiarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 120, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3), "Cliente Encontrado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Condensed", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("DNI: ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Correo: ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        numCuentaField2.setBackground(new java.awt.Color(255, 255, 255));
        numCuentaField2.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        numCuentaField2.addActionListener(this::numCuentaField2ActionPerformed);
        jPanel2.add(numCuentaField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, 30));

        numCuentaField3.setBackground(new java.awt.Color(255, 255, 255));
        numCuentaField3.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        numCuentaField3.addActionListener(this::numCuentaField3ActionPerformed);
        jPanel2.add(numCuentaField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 30));

        numCuentaField4.setBackground(new java.awt.Color(255, 255, 255));
        numCuentaField4.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        numCuentaField4.addActionListener(this::numCuentaField4ActionPerformed);
        jPanel2.add(numCuentaField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, 30));

        jLabel11.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fecha de Registro:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 30));

        numCuentaField5.setBackground(new java.awt.Color(255, 255, 255));
        numCuentaField5.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        numCuentaField5.addActionListener(this::numCuentaField5ActionPerformed);
        jPanel2.add(numCuentaField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 30));

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Edad:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 30));

        numCuentaField6.setBackground(new java.awt.Color(255, 255, 255));
        numCuentaField6.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        numCuentaField6.addActionListener(this::numCuentaField6ActionPerformed);
        jPanel2.add(numCuentaField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 440, 320));

        limpiarBtn1.setBackground(new java.awt.Color(204, 0, 0));
        limpiarBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        limpiarBtn1.setText("Buscar");
        limpiarBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarBtn1.setDefaultCapable(false);
        limpiarBtn1.addActionListener(this::limpiarBtn1ActionPerformed);
        jPanel1.add(limpiarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 120, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarBtnActionPerformed

    private void numCuentaField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField1ActionPerformed

    private void numCuentaField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField2ActionPerformed

    private void numCuentaField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField3ActionPerformed

    private void numCuentaField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField4ActionPerformed

    private void numCuentaField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField5ActionPerformed

    private void limpiarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarBtn1ActionPerformed

    private void numCuentaField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limpiarBtn;
    private javax.swing.JButton limpiarBtn1;
    private javax.swing.JTextField numCuentaField1;
    private javax.swing.JTextField numCuentaField2;
    private javax.swing.JTextField numCuentaField3;
    private javax.swing.JTextField numCuentaField4;
    private javax.swing.JTextField numCuentaField5;
    private javax.swing.JTextField numCuentaField6;
    // End of variables declaration//GEN-END:variables
}
