/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Banco.ClasesBase.*;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author thebe
 */
public class MenuEmpleado extends javax.swing.JFrame {
    
    EmpleadoDeposito deposito = new EmpleadoDeposito();
    EmpleadoRetiro retiro = new EmpleadoRetiro();
    EmpleadoRegistrarCliente registrar = new EmpleadoRegistrarCliente();
    EmpleadoConsultarInformacion consultar = new EmpleadoConsultarInformacion();
    EmpleadoMovimientosDeCuenta movimientos = new EmpleadoMovimientosDeCuenta();
    
    CardLayout vista;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuEmpleado.class.getName());

    /**
     * Creates new form MenuEmpleado
     */
    public MenuEmpleado() {
        initComponents();
        vista = (CardLayout) Pnl_vista_principal.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        movCuentaBtn = new javax.swing.JButton();
        rgDepBtn = new javax.swing.JButton();
        rgRetBtn = new javax.swing.JButton();
        rgClienteBtn = new javax.swing.JButton();
        consultaBtn = new javax.swing.JButton();
        Pnl_vista_principal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clienteIcono.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, 110));

        movCuentaBtn.setBackground(new java.awt.Color(204, 0, 0));
        movCuentaBtn.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        movCuentaBtn.setForeground(new java.awt.Color(255, 255, 255));
        movCuentaBtn.setText("Movimientos De Cuenta");
        movCuentaBtn.setBorderPainted(false);
        movCuentaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        movCuentaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                movCuentaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                movCuentaBtnMouseExited(evt);
            }
        });
        movCuentaBtn.addActionListener(this::movCuentaBtnActionPerformed);
        jPanel3.add(movCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 190, 50));

        rgDepBtn.setBackground(new java.awt.Color(204, 0, 0));
        rgDepBtn.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        rgDepBtn.setForeground(new java.awt.Color(255, 255, 255));
        rgDepBtn.setText("Registrar Deposito");
        rgDepBtn.setBorderPainted(false);
        rgDepBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rgDepBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rgDepBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rgDepBtnMouseExited(evt);
            }
        });
        rgDepBtn.addActionListener(this::rgDepBtnActionPerformed);
        jPanel3.add(rgDepBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 50));

        rgRetBtn.setBackground(new java.awt.Color(204, 0, 0));
        rgRetBtn.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        rgRetBtn.setForeground(new java.awt.Color(255, 255, 255));
        rgRetBtn.setText("Registrar Retiro");
        rgRetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rgRetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rgRetBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rgRetBtnMouseExited(evt);
            }
        });
        rgRetBtn.addActionListener(this::rgRetBtnActionPerformed);
        jPanel3.add(rgRetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 50));

        rgClienteBtn.setBackground(new java.awt.Color(204, 0, 0));
        rgClienteBtn.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        rgClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        rgClienteBtn.setText("Registrar Nuevo Cliente");
        rgClienteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rgClienteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rgClienteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rgClienteBtnMouseExited(evt);
            }
        });
        rgClienteBtn.addActionListener(this::rgClienteBtnActionPerformed);
        jPanel3.add(rgClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 50));

        consultaBtn.setBackground(new java.awt.Color(204, 0, 0));
        consultaBtn.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        consultaBtn.setForeground(new java.awt.Color(255, 255, 255));
        consultaBtn.setText("Consultar Informacion Clientes");
        consultaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaBtnMouseExited(evt);
            }
        });
        consultaBtn.addActionListener(this::consultaBtnActionPerformed);
        jPanel3.add(consultaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 610));

        Pnl_vista_principal.setBackground(new java.awt.Color(204, 0, 0));
        Pnl_vista_principal.setLayout(new java.awt.CardLayout());
        jPanel1.add(Pnl_vista_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 730, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rgDepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgDepBtnActionPerformed
        Pnl_vista_principal.add(deposito, "deposito");
        vista.show(Pnl_vista_principal, "deposito");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_rgDepBtnActionPerformed

    private void rgDepBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgDepBtnMouseEntered
        rgDepBtn.setBackground(new Color(255,255,255));
        rgDepBtn.setForeground(new Color(0,0,0));         // letras negras
    }//GEN-LAST:event_rgDepBtnMouseEntered

    private void rgDepBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgDepBtnMouseExited
        rgDepBtn.setBackground(new Color(204,0,0));
        rgDepBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_rgDepBtnMouseExited

    private void rgRetBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgRetBtnMouseEntered
        rgRetBtn.setBackground(new Color(255,255,255));
        rgRetBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_rgRetBtnMouseEntered

    private void rgRetBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgRetBtnMouseExited
        rgRetBtn.setBackground(new Color(204,0,0));
        rgRetBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_rgRetBtnMouseExited

    private void rgClienteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgClienteBtnMouseEntered
        rgClienteBtn.setBackground(new Color(255,255,255));
        rgClienteBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_rgClienteBtnMouseEntered

    private void rgClienteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgClienteBtnMouseExited
        rgClienteBtn.setBackground(new Color(204,0,0));
        rgClienteBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_rgClienteBtnMouseExited

    private void consultaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaBtnMouseEntered
        consultaBtn.setBackground(new Color(255,255,255));
        consultaBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_consultaBtnMouseEntered

    private void consultaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaBtnMouseExited
        consultaBtn.setBackground(new Color(204,0,0));
        consultaBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_consultaBtnMouseExited

    private void movCuentaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movCuentaBtnMouseEntered
        movCuentaBtn.setBackground(new Color(255,255,255));
        movCuentaBtn.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_movCuentaBtnMouseEntered

    private void movCuentaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movCuentaBtnMouseExited
        movCuentaBtn.setBackground(new Color(204,0,0));
        movCuentaBtn.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_movCuentaBtnMouseExited

    private void consultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBtnActionPerformed
        Pnl_vista_principal.add(consultar, "consultar");
        vista.show(Pnl_vista_principal, "consultar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_consultaBtnActionPerformed

    private void rgRetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgRetBtnActionPerformed
        Pnl_vista_principal.add(retiro, "retiro");
        vista.show(Pnl_vista_principal, "retiro");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_rgRetBtnActionPerformed

    private void rgClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgClienteBtnActionPerformed
        Pnl_vista_principal.add(registrar, "registrar");
        vista.show(Pnl_vista_principal, "registrar");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_rgClienteBtnActionPerformed

    private void movCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movCuentaBtnActionPerformed
        Pnl_vista_principal.add(movimientos, "movimientos");
        vista.show(Pnl_vista_principal, "movimientos");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_movCuentaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_vista_principal;
    private javax.swing.JButton consultaBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton movCuentaBtn;
    private javax.swing.JButton rgClienteBtn;
    private javax.swing.JButton rgDepBtn;
    private javax.swing.JButton rgRetBtn;
    // End of variables declaration//GEN-END:variables
}
