/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author thebe
 */
public class EmpleadoDeposito extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadoDeposito
     */
    public EmpleadoDeposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        numCuentaField = new javax.swing.JTextField();
        nomTitularField = new javax.swing.JTextField();
        montoField = new javax.swing.JTextField();
        depositarBtn = new javax.swing.JButton();
        limpiarBtn = new javax.swing.JButton();
        boleta = new javax.swing.JPanel();
        numTransField = new javax.swing.JTextField();
        numField = new javax.swing.JTextField();
        depositadoField = new javax.swing.JTextField();
        salAnteriorField = new javax.swing.JTextField();
        salActualField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Deposito Bancario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserte Datos Del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Condensed", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jLabel2.setText("NOMBRE DEL TITULAR: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel3.setText("DATOS DE LA TRANSACCION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jLabel4.setText("DNI: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel6.setText("DATOS DEL CLIENTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jLabel7.setText("NUMERO DE LA CUENTA: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        jLabel8.setText("MONTO A DEPOSITAR: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        dniField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        dniField.addActionListener(this::dniFieldActionPerformed);
        jPanel1.add(dniField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 91, 170, 30));

        numCuentaField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField.addActionListener(this::numCuentaFieldActionPerformed);
        jPanel1.add(numCuentaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, 30));

        nomTitularField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        nomTitularField.addActionListener(this::nomTitularFieldActionPerformed);
        jPanel1.add(nomTitularField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 121, 170, 30));

        montoField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        montoField.addActionListener(this::montoFieldActionPerformed);
        jPanel1.add(montoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 81, 170, 30));

        depositarBtn.setBackground(new java.awt.Color(204, 0, 0));
        depositarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        depositarBtn.setForeground(new java.awt.Color(255, 255, 255));
        depositarBtn.setText("Limpiar");
        depositarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositarBtn.setDefaultCapable(false);
        jPanel1.add(depositarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, 40));

        limpiarBtn.setBackground(new java.awt.Color(204, 0, 0));
        limpiarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarBtn.setText("Depositar");
        limpiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarBtn.setDefaultCapable(false);
        jPanel1.add(limpiarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 40));

        boleta.setBackground(new java.awt.Color(255, 255, 255));
        boleta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3), "Deposito Exitoso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Condensed", 0, 18))); // NOI18N
        boleta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numTransField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numTransField.addActionListener(this::numTransFieldActionPerformed);
        boleta.add(numTransField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 170, 20));

        numField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numField.addActionListener(this::numFieldActionPerformed);
        boleta.add(numField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 170, -1));

        depositadoField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        depositadoField.addActionListener(this::depositadoFieldActionPerformed);
        boleta.add(depositadoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 170, -1));

        salAnteriorField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        salAnteriorField.addActionListener(this::salAnteriorFieldActionPerformed);
        boleta.add(salAnteriorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 170, -1));

        salActualField.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        salActualField.addActionListener(this::salActualFieldActionPerformed);
        boleta.add(salActualField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 170, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel13.setText("Saldo Actual: ");
        boleta.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel14.setText("Numero de Transaccion: ");
        boleta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel15.setText("Numero de Cuenta: ");
        boleta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel16.setText("Monto Depositado: ");
        boleta.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel17.setText("Saldo Anterior:");
        boleta.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jPanel1.add(boleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 440, 240));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 690, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void dniFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniFieldActionPerformed

    private void numCuentaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaFieldActionPerformed

    private void nomTitularFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTitularFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTitularFieldActionPerformed

    private void montoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoFieldActionPerformed

    private void salActualFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActualFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salActualFieldActionPerformed

    private void numTransFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTransFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTransFieldActionPerformed

    private void numFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numFieldActionPerformed

    private void depositadoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositadoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositadoFieldActionPerformed

    private void salAnteriorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salAnteriorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salAnteriorFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boleta;
    private javax.swing.JTextField depositadoField;
    private javax.swing.JButton depositarBtn;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiarBtn;
    private javax.swing.JTextField montoField;
    private javax.swing.JTextField nomTitularField;
    private javax.swing.JTextField numCuentaField;
    private javax.swing.JTextField numField;
    private javax.swing.JTextField numTransField;
    private javax.swing.JTextField salActualField;
    private javax.swing.JTextField salAnteriorField;
    // End of variables declaration//GEN-END:variables
}
