/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import java.awt.Color;

/**
 *
 * @author thebe
 */
public class MenuCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCliente.class.getName());

    /**
     * Creates new form MenuCliente
     */
    public MenuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bienvenidaLabel = new javax.swing.JLabel();
        cerrarBtn = new javax.swing.JPanel();
        cerrarLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        retLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        depLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        transLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        consultaLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        consultaMisLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Untitled (3).png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 550, 460));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Untitled (4).png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 110));

        bienvenidaLabel.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        bienvenidaLabel.setText("Bienvenido Estimado Cliente");
        jPanel3.add(bienvenidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        cerrarBtn.setBackground(new java.awt.Color(204, 0, 0));
        cerrarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrarLabel.setBackground(new java.awt.Color(204, 0, 0));
        cerrarLabel.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        cerrarLabel.setForeground(new java.awt.Color(255, 255, 255));
        cerrarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarLabel.setText("Cerrar Sesion");
        cerrarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarLabelMouseExited(evt);
            }
        });
        cerrarBtn.add(cerrarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel3.add(cerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 140, 40));

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        retLabel.setForeground(java.awt.Color.white);
        retLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retLabel.setText("Procesar Retiro");
        retLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(retLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 350, 40));

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        depLabel.setForeground(java.awt.Color.white);
        depLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depLabel.setText("Procesar Deposito");
        depLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(depLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 350, 40));

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        transLabel.setForeground(java.awt.Color.white);
        transLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transLabel.setText("Ver Mis Transacciones");
        transLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(transLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 350, 40));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        consultaLabel.setForeground(java.awt.Color.white);
        consultaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultaLabel.setText("Consultar Cuenta");
        consultaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(consultaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 350, 40));

        jPanel7.setBackground(new java.awt.Color(204, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultaMisLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        consultaMisLabel.setForeground(java.awt.Color.white);
        consultaMisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultaMisLabel.setText("Consultar Mis Cuentas");
        consultaMisLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(consultaMisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 350, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 400, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarLabelMouseEntered
        cerrarBtn.setBackground(new Color(255, 55, 47));
    }//GEN-LAST:event_cerrarLabelMouseEntered

    private void cerrarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarLabelMouseExited
        cerrarBtn.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_cerrarLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JPanel cerrarBtn;
    private javax.swing.JLabel cerrarLabel;
    private javax.swing.JLabel consultaLabel;
    private javax.swing.JLabel consultaMisLabel;
    private javax.swing.JLabel depLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel retLabel;
    private javax.swing.JLabel transLabel;
    // End of variables declaration//GEN-END:variables
}
