/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author thebe
 */
public class MenuEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuEmpleado.class.getName());

    /**
     * Creates new form MenuEmpleado
     */
    public MenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BienvenidaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acClienteLabel = new javax.swing.JLabel();
        rgClienteBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        movClienteBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        eliClienteBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        acCuentaLabel = new javax.swing.JLabel();
        abrirCtBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        agTitularBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        movCuentaBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        conTitularesBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        conCuentaBtn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        eliCuentaBtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        transaccionesLabel = new javax.swing.JLabel();
        depositoBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        retiroBtn = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        transferenciaBtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        cerrarBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Lateral.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 550, 460));

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BienvenidaLabel.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        BienvenidaLabel.setText("Bienvenido Estimado Empleado");
        jPanel2.add(BienvenidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empleadoIcono.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 110));

        acClienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        acClienteLabel.setText("ACCIONES PARA CLIENTE");
        jPanel2.add(acClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        rgClienteBtn.setBackground(new java.awt.Color(204, 0, 0));
        rgClienteBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registrar Cliente");
        rgClienteBtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(rgClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 30));

        movClienteBtn.setBackground(new java.awt.Color(204, 0, 0));
        movClienteBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Consultar Movimientos");
        movClienteBtn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(movClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 30));

        eliClienteBtn.setBackground(new java.awt.Color(204, 0, 0));
        eliClienteBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Eliminar Cliente");
        eliClienteBtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(eliClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 160, 30));

        acCuentaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        acCuentaLabel.setText("ACCIONES PARA CUENTA");
        jPanel2.add(acCuentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        abrirCtBtn.setBackground(new java.awt.Color(204, 0, 0));
        abrirCtBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Abrir Cuenta");
        abrirCtBtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(abrirCtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, 30));

        agTitularBtn.setBackground(new java.awt.Color(204, 0, 0));
        agTitularBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar Titular");
        agTitularBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(agTitularBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 160, 30));

        movCuentaBtn.setBackground(new java.awt.Color(204, 0, 0));
        movCuentaBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Consultar Movimientos");
        movCuentaBtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(movCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 160, 30));

        conTitularesBtn.setBackground(new java.awt.Color(204, 0, 0));
        conTitularesBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Consultar Titulares");
        conTitularesBtn.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(conTitularesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 30));

        conCuentaBtn.setBackground(new java.awt.Color(204, 0, 0));
        conCuentaBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Consultar Cuenta");
        conCuentaBtn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(conCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 30));

        eliCuentaBtn.setBackground(new java.awt.Color(204, 0, 0));
        eliCuentaBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Eliminar Cuenta");
        eliCuentaBtn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(eliCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 160, 30));

        transaccionesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        transaccionesLabel.setText("TRANSACCIONES");
        jPanel2.add(transaccionesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        depositoBtn.setBackground(new java.awt.Color(204, 0, 0));
        depositoBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Procesar Deposito");
        depositoBtn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(depositoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 160, 30));

        retiroBtn.setBackground(new java.awt.Color(204, 0, 0));
        retiroBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Procesar Retiro");
        retiroBtn.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(retiroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 160, 30));

        transferenciaBtn.setBackground(new java.awt.Color(204, 0, 0));
        transferenciaBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Procesar Transferencia");
        transferenciaBtn.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel2.add(transferenciaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 160, 30));

        cerrarBtn.setBackground(new java.awt.Color(204, 0, 0));
        cerrarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CERRAR SESION");
        cerrarBtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanel2.add(cerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 160, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 530, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidaLabel;
    private javax.swing.JPanel abrirCtBtn;
    private javax.swing.JLabel acClienteLabel;
    private javax.swing.JLabel acCuentaLabel;
    private javax.swing.JPanel agTitularBtn;
    private javax.swing.JPanel cerrarBtn;
    private javax.swing.JPanel conCuentaBtn;
    private javax.swing.JPanel conTitularesBtn;
    private javax.swing.JPanel depositoBtn;
    private javax.swing.JPanel eliClienteBtn;
    private javax.swing.JPanel eliCuentaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel movClienteBtn;
    private javax.swing.JPanel movCuentaBtn;
    private javax.swing.JPanel retiroBtn;
    private javax.swing.JPanel rgClienteBtn;
    private javax.swing.JLabel transaccionesLabel;
    private javax.swing.JPanel transferenciaBtn;
    // End of variables declaration//GEN-END:variables
}
