/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author thebe
 */
public class EmpleadoMovimientosDeCuenta extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadoMovimientosDeCuenta
     */
    public EmpleadoMovimientosDeCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        numCuentaField1 = new javax.swing.JTextField();
        limpiarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numCuentaField = new javax.swing.JTextField();
        numCuentaField2 = new javax.swing.JTextField();
        numCuentaField3 = new javax.swing.JTextField();
        numCuentaField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numCuentaField5 = new javax.swing.JTextField();
        numCuentaField6 = new javax.swing.JTextField();
        numCuentaField7 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Movimientos de Cuenta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Buscar Movimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Condensed", 0, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID de transaccion:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, 40));

        numCuentaField1.setBackground(new java.awt.Color(255, 255, 255));
        numCuentaField1.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        numCuentaField1.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField1.addActionListener(this::numCuentaField1ActionPerformed);
        jPanel1.add(numCuentaField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 170, 40));

        limpiarBtn.setBackground(new java.awt.Color(204, 0, 0));
        limpiarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        limpiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarBtn.setText("Buscar");
        limpiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarBtn.setDefaultCapable(false);
        limpiarBtn.addActionListener(this::limpiarBtnActionPerformed);
        jPanel1.add(limpiarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 120, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3), "Transaccion Encontrada", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Roboto Condensed", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(null);
        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Operador");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel9.setBackground(null);
        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Numero de Transaccion:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel10.setBackground(null);
        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipo:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel12.setBackground(null);
        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Fecha:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        numCuentaField.setBackground(null);
        numCuentaField.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        numCuentaField.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCuentaField.addActionListener(this::numCuentaFieldActionPerformed);
        jPanel2.add(numCuentaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 170, 30));

        numCuentaField2.setBackground(null);
        numCuentaField2.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        numCuentaField2.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCuentaField2.addActionListener(this::numCuentaField2ActionPerformed);
        jPanel2.add(numCuentaField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 170, 30));

        numCuentaField3.setBackground(null);
        numCuentaField3.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        numCuentaField3.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCuentaField3.addActionListener(this::numCuentaField3ActionPerformed);
        jPanel2.add(numCuentaField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 170, 30));

        numCuentaField4.setBackground(null);
        numCuentaField4.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        numCuentaField4.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCuentaField4.addActionListener(this::numCuentaField4ActionPerformed);
        jPanel2.add(numCuentaField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 170, 30));

        jLabel11.setBackground(null);
        jLabel11.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Monto:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel13.setBackground(null);
        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Saldo Anterior:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel14.setBackground(null);
        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Saldo Final");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        numCuentaField5.setBackground(null);
        numCuentaField5.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        numCuentaField5.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCuentaField5.addActionListener(this::numCuentaField5ActionPerformed);
        jPanel2.add(numCuentaField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 170, 30));

        numCuentaField6.setBackground(null);
        numCuentaField6.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        numCuentaField6.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCuentaField6.addActionListener(this::numCuentaField6ActionPerformed);
        jPanel2.add(numCuentaField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 170, 30));

        numCuentaField7.setBackground(null);
        numCuentaField7.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        numCuentaField7.setForeground(new java.awt.Color(0, 0, 0));
        numCuentaField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numCuentaField7.addActionListener(this::numCuentaField7ActionPerformed);
        jPanel2.add(numCuentaField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 610, 370));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 170, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 880, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void numCuentaField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField1ActionPerformed

    private void limpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarBtnActionPerformed

    private void numCuentaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaFieldActionPerformed

    private void numCuentaField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField2ActionPerformed

    private void numCuentaField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField3ActionPerformed

    private void numCuentaField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField4ActionPerformed

    private void numCuentaField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField5ActionPerformed

    private void numCuentaField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField6ActionPerformed

    private void numCuentaField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuentaField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCuentaField7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limpiarBtn;
    private javax.swing.JTextField numCuentaField;
    private javax.swing.JTextField numCuentaField1;
    private javax.swing.JTextField numCuentaField2;
    private javax.swing.JTextField numCuentaField3;
    private javax.swing.JTextField numCuentaField4;
    private javax.swing.JTextField numCuentaField5;
    private javax.swing.JTextField numCuentaField6;
    private javax.swing.JTextField numCuentaField7;
    // End of variables declaration//GEN-END:variables
}
