/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.panelAdmin;

import Banco.BancoExceptions.BancoException;
import Banco.ClasesBase.Transaccion;
import Banco.ClasesBase.Transferencia;
import Banco.ClasesBase.Usuario;
import Banco.GestorPrincipal.Banco;
public class AdminTransferencia extends javax.swing.JPanel {

    /**
     * Creates new form AdminTransferencia
     */
    private Banco banco;
    private Usuario usuarioActual;
    public AdminTransferencia(Banco banco) {
        initComponents();
        this.banco = banco;
        this.usuarioActual = usuarioActual;
        boletaTransferencia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        origenEntrada = new javax.swing.JTextField();
        destinoEntrada = new javax.swing.JTextField();
        montoEntrada = new javax.swing.JTextField();
        claveEntrada = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        transferir = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        boletaTransferencia = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cuentaDestinoL = new javax.swing.JLabel();
        numTransaccion = new javax.swing.JLabel();
        cuentaOrigenL = new javax.swing.JLabel();
        dniCliente = new javax.swing.JLabel();
        montoL = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        avisoFondo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transferencia");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Clave:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 93, 43));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Numº Cuenta Origen: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, 43));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Numº Cuenta Destino: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 43));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Monto:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 93, 43));

        origenEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        origenEntrada.addActionListener(this::origenEntradaActionPerformed);
        jPanel2.add(origenEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, -1));

        destinoEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinoEntrada.addActionListener(this::destinoEntradaActionPerformed);
        jPanel2.add(destinoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 230, -1));

        montoEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(montoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 170, -1));

        claveEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(claveEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 169, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 170, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 169, 10));

        transferir.setBackground(new java.awt.Color(204, 0, 0));
        transferir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transferir.setForeground(new java.awt.Color(255, 255, 255));
        transferir.setText("TRANSFERIR");
        transferir.addActionListener(this::transferirActionPerformed);
        jPanel2.add(transferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 140, 40));

        limpiar.setBackground(new java.awt.Color(204, 0, 0));
        limpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(this::limpiarActionPerformed);
        jPanel2.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 90, 40));

        boletaTransferencia.setBackground(new java.awt.Color(255, 255, 255));
        boletaTransferencia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true), "Transferencia Exitosa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        boletaTransferencia.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                boletaTransferenciaComponentHidden(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Num Transaccion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Cuenta Origen:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DNI Cliente:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Cuenta Destino:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Monto:");

        cuentaDestinoL.setBackground(new java.awt.Color(0, 153, 153));
        cuentaDestinoL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuentaDestinoL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cuentaDestinoL.setText(".");
        cuentaDestinoL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        numTransaccion.setBackground(new java.awt.Color(0, 153, 153));
        numTransaccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numTransaccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numTransaccion.setText(".");
        numTransaccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cuentaOrigenL.setBackground(new java.awt.Color(0, 153, 153));
        cuentaOrigenL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuentaOrigenL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cuentaOrigenL.setText(".");
        cuentaOrigenL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        dniCliente.setBackground(new java.awt.Color(0, 153, 153));
        dniCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dniCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dniCliente.setText(".");
        dniCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        montoL.setBackground(new java.awt.Color(0, 153, 153));
        montoL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        montoL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        montoL.setText(".");
        montoL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout boletaTransferenciaLayout = new javax.swing.GroupLayout(boletaTransferencia);
        boletaTransferencia.setLayout(boletaTransferenciaLayout);
        boletaTransferenciaLayout.setHorizontalGroup(
            boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boletaTransferenciaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(montoL, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boletaTransferenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cuentaOrigenL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(cuentaDestinoL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(numTransaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        boletaTransferenciaLayout.setVerticalGroup(
            boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boletaTransferenciaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuentaOrigenL))
                .addGap(25, 25, 25)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuentaDestinoL))
                .addGap(18, 18, 18)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montoL))
                .addGap(16, 16, 16)
                .addGroup(boletaTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniCliente)))
        );

        jPanel2.add(boletaTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 380, 310));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, 10));

        avisoFondo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        avisoFondo.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(avisoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 820, 140));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void origenEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenEntradaActionPerformed

    private void destinoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoEntradaActionPerformed
    private void limpiar() {
        claveEntrada.setText("");
        montoEntrada.setText("");
        origenEntrada.setText("");
        destinoEntrada.setText("");
    }
    private void transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirActionPerformed
        try {
            String clave = new String(claveEntrada.getPassword());
            String monto = montoEntrada.getText();
            String cuentaOrigen = origenEntrada.getText();
            String cuentaDestino = destinoEntrada.getText();

            Transferencia nuevaTransaccion = banco.getgTransacciones().procesarTransferencia(usuarioActual, cuentaOrigen, cuentaDestino, monto, String.valueOf(usuarioActual.getDni()), clave);

            numTransaccion.setText(String.valueOf(nuevaTransaccion.getIdTransaccion()));
            cuentaOrigenL.setText(cuentaOrigen);
            cuentaDestinoL.setText(cuentaDestino);
            montoL.setText(monto);
            dniCliente.setText(String.valueOf(usuarioActual.getDni()));

        } catch(Exception e) {
            limpiar();
            avisoFondo.setText(e.getMessage());
        }

    }//GEN-LAST:event_transferirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
        avisoFondo.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void boletaTransferenciaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_boletaTransferenciaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_boletaTransferenciaComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoFondo;
    private javax.swing.JPanel boletaTransferencia;
    private javax.swing.JPasswordField claveEntrada;
    private javax.swing.JLabel cuentaDestinoL;
    private javax.swing.JLabel cuentaOrigenL;
    private javax.swing.JTextField destinoEntrada;
    private javax.swing.JLabel dniCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField montoEntrada;
    private javax.swing.JLabel montoL;
    private javax.swing.JLabel numTransaccion;
    private javax.swing.JTextField origenEntrada;
    private javax.swing.JButton transferir;
    // End of variables declaration//GEN-END:variables
}
