/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.panelCliente.Paneles;

/**
 *
 * @author camer
 */
public class Pnl_Transferir extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_Transferir
     */
    public Pnl_Transferir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        origenEntrada = new javax.swing.JTextField();
        destinoEntrada = new javax.swing.JTextField();
        montoEntrada = new javax.swing.JTextField();
        claveEntrada = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        transferir = new javax.swing.JButton();
        avisoCtaOrigen = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        avisoCtaOrigen1 = new javax.swing.JLabel();
        avisoCtaOrigen2 = new javax.swing.JLabel();
        avisoCtaOrigen3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cuentaDestino = new javax.swing.JLabel();
        numTransaccion = new javax.swing.JLabel();
        cuentaOrigen = new javax.swing.JLabel();
        dniCliente = new javax.swing.JLabel();
        monto = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transferencia");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Ingresar Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Clave:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 93, 43));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Numº Cuenta Origen: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, 43));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numº Cuenta Destino: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, 43));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Monto:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 93, 43));

        origenEntrada.setBackground(new java.awt.Color(255, 255, 255));
        origenEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        origenEntrada.setForeground(new java.awt.Color(0, 0, 0));
        origenEntrada.addActionListener(this::origenEntradaActionPerformed);
        jPanel2.add(origenEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 230, -1));

        destinoEntrada.setBackground(new java.awt.Color(255, 255, 255));
        destinoEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinoEntrada.setForeground(new java.awt.Color(0, 0, 0));
        destinoEntrada.addActionListener(this::destinoEntradaActionPerformed);
        jPanel2.add(destinoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 230, -1));

        montoEntrada.setBackground(new java.awt.Color(255, 255, 255));
        montoEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        montoEntrada.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(montoEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 170, -1));

        claveEntrada.setBackground(new java.awt.Color(255, 255, 255));
        claveEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        claveEntrada.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(claveEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 169, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 230, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 170, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 169, 10));

        transferir.setBackground(new java.awt.Color(204, 0, 0));
        transferir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transferir.setForeground(new java.awt.Color(255, 255, 255));
        transferir.setText("TRANSFERIR");
        jPanel2.add(transferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 40));

        avisoCtaOrigen.setBackground(new java.awt.Color(51, 51, 51));
        avisoCtaOrigen.setForeground(new java.awt.Color(0, 0, 0));
        avisoCtaOrigen.setText(".");
        jPanel2.add(avisoCtaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 170, -1));

        limpiar.setBackground(new java.awt.Color(204, 0, 0));
        limpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(this::limpiarActionPerformed);
        jPanel2.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, 40));

        avisoCtaOrigen1.setBackground(new java.awt.Color(51, 51, 51));
        avisoCtaOrigen1.setForeground(new java.awt.Color(0, 0, 0));
        avisoCtaOrigen1.setText(".");
        jPanel2.add(avisoCtaOrigen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, -1));

        avisoCtaOrigen2.setBackground(new java.awt.Color(51, 51, 51));
        avisoCtaOrigen2.setForeground(new java.awt.Color(0, 0, 0));
        avisoCtaOrigen2.setText(".");
        jPanel2.add(avisoCtaOrigen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, -1));

        avisoCtaOrigen3.setBackground(new java.awt.Color(51, 51, 51));
        avisoCtaOrigen3.setForeground(new java.awt.Color(0, 0, 0));
        avisoCtaOrigen3.setText(".");
        jPanel2.add(avisoCtaOrigen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 170, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true), "Transferencia Exitosa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentHidden(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Num Transaccion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cuenta Origen:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DNI Cliente:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cuenta Destino:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Monto:");

        cuentaDestino.setBackground(new java.awt.Color(0, 153, 153));
        cuentaDestino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuentaDestino.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cuentaDestino.setText(".");
        cuentaDestino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        numTransaccion.setBackground(new java.awt.Color(0, 153, 153));
        numTransaccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numTransaccion.setForeground(new java.awt.Color(0, 0, 0));
        numTransaccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numTransaccion.setText(".");
        numTransaccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cuentaOrigen.setBackground(new java.awt.Color(0, 153, 153));
        cuentaOrigen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cuentaOrigen.setForeground(new java.awt.Color(0, 0, 0));
        cuentaOrigen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cuentaOrigen.setText(".");
        cuentaOrigen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        dniCliente.setBackground(new java.awt.Color(0, 153, 153));
        dniCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dniCliente.setForeground(new java.awt.Color(0, 0, 0));
        dniCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dniCliente.setText(".");
        dniCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        monto.setBackground(new java.awt.Color(0, 153, 153));
        monto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        monto.setForeground(new java.awt.Color(0, 0, 0));
        monto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        monto.setText(".");
        monto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cuentaOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(cuentaDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(numTransaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuentaOrigen))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuentaDestino))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monto))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniCliente)))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 380, 310));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 230, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void destinoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoEntradaActionPerformed

    private void origenEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenEntradaActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed

    private void jPanel3ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3ComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoCtaOrigen;
    private javax.swing.JLabel avisoCtaOrigen1;
    private javax.swing.JLabel avisoCtaOrigen2;
    private javax.swing.JLabel avisoCtaOrigen3;
    private javax.swing.JPasswordField claveEntrada;
    private javax.swing.JLabel cuentaDestino;
    private javax.swing.JLabel cuentaOrigen;
    private javax.swing.JTextField destinoEntrada;
    private javax.swing.JLabel dniCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel monto;
    private javax.swing.JTextField montoEntrada;
    private javax.swing.JLabel numTransaccion;
    private javax.swing.JTextField origenEntrada;
    private javax.swing.JButton transferir;
    // End of variables declaration//GEN-END:variables
}
